version: "3.0"

services:
  data_api:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./volumes_data:/usr/src/app/volumes_data
    depends_on:
      - form_db
    restart: always

  form_db:
    container_name: form_db
    image: postgres:14-alpine
    restart: always
    environment: 
      - DATABASE_HOST=form_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=FormData  
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  logvolume01: {}
  volumes_data:
  pgdata: